# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniq_key', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='id',
        ),
        migrations.AlterField(
            model_name='key',
            name='value',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
