# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniq_key', '0002_auto_20160519_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='status',
            field=models.CharField(choices=[('N', 'not_issued'), ('I', 'issued'), ('R', 'repaid')], default='N', max_length=1),
        ),
    ]
